"""add task leases

Revision ID: 4bc16aaaa662
Revises: 008f184b68a0
Create Date: 2026-05-11 19:01:22.423048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc16aaaa662'
down_revision: Union[str, Sequence[str], None] = '008f184b68a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'lease_expires_at')
    # ### end Alembic commands ###
