"""add execution logs

Revision ID: 6357f26b1fd4
Revises: 8793075abf22
Create Date: 2026-05-12 00:17:35.104152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6357f26b1fd4'
down_revision: Union[str, Sequence[str], None] = '8793075abf22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_executions', sa.Column('logs', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_executions', 'logs')
    # ### end Alembic commands ###
